package hu.csega.editors.anm.layer5.files.storage;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;

import hu.csega.editors.anm.layer4.data.migration.LegacyAnimationMigrator;
import hu.csega.games.library.legacy.animationdata.CModelData;

public class TestLoadTestAnimation {

	public static void main(String[] args) {
		ByteArrayInputStream stream = new ByteArrayInputStream(HUMAN_RUN_ANM.getBytes(StandardCharsets.UTF_8));
		Object result = LegacyAnimationParser.parseAnimationFile(stream);
		System.out.println("Result class: " + (result == null ? null : result.getClass().getName()));

		Object migratedObject = null;
		if(result instanceof CModelData) {
			migratedObject = LegacyAnimationMigrator.migrate((CModelData)result);
		}

		System.out.println("Migrated object class: " + (result == null ? null : result.getClass().getName()));
		System.out.flush();

		AnimationExportGenerator.generateExport(migratedObject, System.out);
		System.out.flush();
	}

	private static final String HUMAN_RUN_ANM = "<meta description=\"Xml Data Binder\" version=\"0.5.0000\">\n" +
			"  <Legacy.CModelData>\n" +
			"    <parts>\n" +
			"      <Legacy.CPartData>\n" +
			"        <connections />\n" +
			"        <center_point>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>-0,025</X>\n" +
			"            <Y>0,725</Y>\n" +
			"            <Z>-0,1</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>0</X>\n" +
			"            <Y>0</Y>\n" +
			"            <Z>0</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"        </center_point>\n" +
			"        <mesh_file>htorso.x</mesh_file>\n" +
			"        <model_transform>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"        </model_transform>\n" +
			"      </Legacy.CPartData>\n" +
			"      <Legacy.CPartData>\n" +
			"        <connections>\n" +
			"          <Legacy.CConnection>\n" +
			"            <point>\n" +
			"              <X>0</X>\n" +
			"              <Y>0</Y>\n" +
			"              <Z>0</Z>\n" +
			"            </point>\n" +
			"            <object_index>-2</object_index>\n" +
			"            <connection_index>-1</connection_index>\n" +
			"          </Legacy.CConnection>\n" +
			"        </connections>\n" +
			"        <center_point>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>-0,175</X>\n" +
			"            <Y>0,7990385</Y>\n" +
			"            <Z>-0,1476416</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>-0,155</X>\n" +
			"            <Y>0,05499999</Y>\n" +
			"            <Z>-0,00999999</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"        </center_point>\n" +
			"        <mesh_file>harm_upper.x</mesh_file>\n" +
			"        <model_transform>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>0,9210612</M22>\n" +
			"            <M23>0,3894184</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>-0,3894184</M32>\n" +
			"            <M33>0,9210612</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"        </model_transform>\n" +
			"      </Legacy.CPartData>\n" +
			"      <Legacy.CPartData>\n" +
			"        <connections />\n" +
			"        <center_point>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>0,125</X>\n" +
			"            <Y>0,775</Y>\n" +
			"            <Z>-0,1</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>0,15</X>\n" +
			"            <Y>0,05</Y>\n" +
			"            <Z>0</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"        </center_point>\n" +
			"        <mesh_file>harm_upper.x</mesh_file>\n" +
			"        <model_transform>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"        </model_transform>\n" +
			"      </Legacy.CPartData>\n" +
			"      <Legacy.CPartData>\n" +
			"        <connections />\n" +
			"        <center_point>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>-0,2177902</X>\n" +
			"            <Y>0,5</Y>\n" +
			"            <Z>-0,05999999</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>-0,1927902</X>\n" +
			"            <Y>-0,225</Y>\n" +
			"            <Z>0,04000001</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"        </center_point>\n" +
			"        <mesh_file>harm_lower.x</mesh_file>\n" +
			"        <model_transform>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"        </model_transform>\n" +
			"      </Legacy.CPartData>\n" +
			"      <Legacy.CPartData>\n" +
			"        <connections />\n" +
			"        <center_point>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>0,08918539</X>\n" +
			"            <Y>0,5009862</Y>\n" +
			"            <Z>-0,06200678</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>0,1141854</X>\n" +
			"            <Y>-0,2240138</Y>\n" +
			"            <Z>0,03799322</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"        </center_point>\n" +
			"        <mesh_file>harm_lower.x</mesh_file>\n" +
			"        <model_transform>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"        </model_transform>\n" +
			"      </Legacy.CPartData>\n" +
			"      <Legacy.CPartData>\n" +
			"        <connections />\n" +
			"        <center_point>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>-0,08051979</X>\n" +
			"            <Y>1,285225E-07</Y>\n" +
			"            <Z>-0,1</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>-0,05551979</X>\n" +
			"            <Y>-0,7249999</Y>\n" +
			"            <Z>0</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"        </center_point>\n" +
			"        <mesh_file>hleg_upper.x</mesh_file>\n" +
			"        <model_transform>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"        </model_transform>\n" +
			"      </Legacy.CPartData>\n" +
			"      <Legacy.CPartData>\n" +
			"        <connections />\n" +
			"        <center_point>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>0,03419962</X>\n" +
			"            <Y>2,477318E-07</Y>\n" +
			"            <Z>-0,1</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>0,05919962</X>\n" +
			"            <Y>-0,7249998</Y>\n" +
			"            <Z>0</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"        </center_point>\n" +
			"        <mesh_file>hleg_upper.x</mesh_file>\n" +
			"        <model_transform>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"        </model_transform>\n" +
			"      </Legacy.CPartData>\n" +
			"      <Legacy.CPartData>\n" +
			"        <connections />\n" +
			"        <center_point>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>-0,08419965</X>\n" +
			"            <Y>2,477318E-07</Y>\n" +
			"            <Z>-0,1089793</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>-0,05919965</X>\n" +
			"            <Y>-0,7249998</Y>\n" +
			"            <Z>-0,008979321</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"        </center_point>\n" +
			"        <mesh_file>hleg_lower.x</mesh_file>\n" +
			"        <model_transform>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"        </model_transform>\n" +
			"      </Legacy.CPartData>\n" +
			"      <Legacy.CPartData>\n" +
			"        <connections />\n" +
			"        <center_point>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>0,03235972</X>\n" +
			"            <Y>2,477318E-07</Y>\n" +
			"            <Z>-0,1089793</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"          <Legacy.Vector3>\n" +
			"            <X>0,05735972</X>\n" +
			"            <Y>-0,7249998</Y>\n" +
			"            <Z>-0,008979321</Z>\n" +
			"          </Legacy.Vector3>\n" +
			"        </center_point>\n" +
			"        <mesh_file>hleg_lower.x</mesh_file>\n" +
			"        <model_transform>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"          <Legacy.Matrix>\n" +
			"            <M11>1</M11>\n" +
			"            <M12>0</M12>\n" +
			"            <M13>0</M13>\n" +
			"            <M14>0</M14>\n" +
			"            <M21>0</M21>\n" +
			"            <M22>1</M22>\n" +
			"            <M23>0</M23>\n" +
			"            <M24>0</M24>\n" +
			"            <M31>0</M31>\n" +
			"            <M32>0</M32>\n" +
			"            <M33>1</M33>\n" +
			"            <M34>0</M34>\n" +
			"            <M41>0</M41>\n" +
			"            <M42>0</M42>\n" +
			"            <M43>0</M43>\n" +
			"            <M44>1</M44>\n" +
			"          </Legacy.Matrix>\n" +
			"        </model_transform>\n" +
			"      </Legacy.CPartData>\n" +
			"    </parts>\n" +
			"    <max_scenes>2</max_scenes>\n" +
			"  </Legacy.CModelData>\n" +
			"</meta>";

}
